### ISSUE TITLE
SOE in "Recipes that generate sources have those sources written out to disk successfully" test

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-gradle-plugin#119]
```
Caused by: java.lang.StackOverflowError
	at org.openrewrite.SourceFile.printAllAsBytes(SourceFile.java:63)
	at org.openrewrite.remote.Remote.printAll(Remote.java:65)
	at org.openrewrite.SourceFile.printAllAsBytes(SourceFile.java:63)
	at org.openrewrite.remote.Remote.printAll(Remote.java:65)
```

**Comment by traceyyoshima** [comment]
fixed by [d7d2bc00](https://github.com/openrewrite/rewrite-gradle-plugin/commit/d7d2bc005373f0565ce522c1f777d3476d34020d)
