### ISSUE TITLE
Plugin version 5.5.0+ fails with NoSuchMethodException

### ISSUE THREAD

**Issue by burtbeckwith** [openrewrite/rewrite-gradle-plugin#70]
I'm trying to run some Java recipes. With v5.5.0 or v5.6.0 running `rewriteRun` or `rewriteDryRun` fails with

```
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: org.openrewrite.java.marker.JavaProvenance.<init>(java.util.UUID, java.lang.String, java.lang.String, org.openrewrite.java.marker.JavaProvenance$BuildTool, org.openrewrite.java.marker.JavaProvenance$JavaVersion, java.util.Set, org.openrewrite.java.marker.JavaProvenance$Publication)
        at org.openrewrite.gradle.RewriteReflectiveFacade$JavaProvenanceBuilder.build(RewriteReflectiveFacade.java:375)
        at org.openrewrite.gradle.AbstractRewriteTask.parse(AbstractRewriteTask.java:212)
        ... 125 more
Caused by: java.lang.NoSuchMethodException: org.openrewrite.java.marker.JavaProvenance.<init>(java.util.UUID, java.lang.String, java.lang.String, org.openrewrite.java.marker.JavaProvenance$BuildTool, org.openrewrite.java.marker.JavaProvenance$JavaVersion, java.util.Set, org.openrewrite.java.marker.JavaProvenance$Publication)
        at org.openrewrite.gradle.RewriteReflectiveFacade$JavaProvenanceBuilder.build(RewriteReflectiveFacade.java:371)
        ... 126 more
```

I tried this in a larger project but a barebones project with no source, settings.gradle

`rootProject.name = 'foo'`

and build.gradle

```
plugins {
    id 'java'
    id 'org.openrewrite.rewrite' version '5.5.0'
}

repositories {
    mavenCentral()
}

rewrite {
    activeRecipe('org.openrewrite.java.cleanup.UnnecessaryThrows')
}
```

fails the same way. Downgrading to version 5.4.1 works.

**Comment by tkvangorder** [comment]
Thanks for reporting the issue @burtbeckwith  

The plugin was using code (reflectively) that was only in the `rewrite-java` 7.11.x branch. Upgrading your `rewrite-gradle-plugin:5.7.0` will resolve this issue and this release should be up on maven central shortly.
