### ISSUE TITLE
CPU Bottleneck when calling `toRealPath` during parsing

### ISSUE THREAD

**Issue by tkvangorder** [openrewrite/rewrite-gradle-plugin#75]
The following thread dump was collected and while working with a design partner. This may be due to Virus scanning software installed on the machine, but we should investigate how to speed this up. 

```
"Execution worker for ':' Thread 13" #466 prio=5 os_prio=31 cpu=633447.32ms elapsed=730.02s tid=0x00007ffdc8f87000 nid=0x57c03 runnable  [0x000070002d677000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.fs.UnixNativeDispatcher.realpath0(java.base@11.0.9/Native Method)
        at sun.nio.fs.UnixNativeDispatcher.realpath(java.base@11.0.9/UnixNativeDispatcher.java:272)
        at sun.nio.fs.UnixPath.toRealPath(java.base@11.0.9/UnixPath.java:857)
        at org.openrewrite.gradle.AbstractRewriteTask.toRealPath(AbstractRewriteTask.java:448)
        at org.openrewrite.gradle.AbstractRewriteTask$$Lambda$1135/0x0000000800e69c40.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(java.base@11.0.9/ReferencePipeline.java:195)
        at java.util.stream.ReferencePipeline$3$1.accept(java.base@11.0.9/ReferencePipeline.java:195)
        at java.util.Iterator.forEachRemaining(java.base@11.0.9/Iterator.java:133)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(java.base@11.0.9/Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(java.base@11.0.9/AbstractPipeline.java:484)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@11.0.9/AbstractPipeline.java:474)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(java.base@11.0.9/ReduceOps.java:913)
        at java.util.stream.AbstractPipeline.evaluate(java.base@11.0.9/AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(java.base@11.0.9/ReferencePipeline.java:578)
        at org.openrewrite.gradle.AbstractRewriteTask.parse(AbstractRewriteTask.java:251)
        at org.openrewrite.gradle.AbstractRewriteTask.lambda$listResults$3(AbstractRewriteTask.java:191)
        at org.openrewrite.gradle.AbstractRewriteTask$$Lambda$1103/0x0000000800e66040.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$7$1.accept(java.base@11.0.9/ReferencePipeline.java:271)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(java.base@11.0.9/ArrayList.java:1655)
        at java.util.stream.AbstractPipeline.copyInto(java.base@11.0.9/AbstractPipeline.java:484)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@11.0.9/AbstractPipeline.java:474)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(java.base@11.0.9/ReduceOps.java:913)
        at java.util.stream.AbstractPipeline.evaluate(java.base@11.0.9/AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(java.base@11.0.9/ReferencePipeline.java:578)
        at org.openrewrite.gradle.AbstractRewriteTask.listResults(AbstractRewriteTask.java:192)
        at org.openrewrite.gradle.RewriteDryRunTask.run(RewriteDryRunTask.java:69)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.9/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.9/NativeMethodAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.9/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@11.0.9/Method.java:566)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:494)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
```

**Comment by jkschneider** [comment]
This was resolved in 917829cca0380db29701d46fe810aa33a283dc62.
